baseURL: http://sfitdb.n1xx1.me/
languageCode: it-it
title: Starfinder Italian Database
menus:
  main: []
  sidebar:
    - name: Creazione del Personaggio
      weight: 1
    - name: Stirpi
      pageRef: /stirpi
      parent: Creazione del Personaggio
      weight: 1
    - name: Background
      pageRef: /background
      parent: Creazione del Personaggio
      weight: 2
    - name: Classi
      pageRef: /classi
      parent: Creazione del Personaggio
      weight: 3
    - name: Archetipi
      pageRef: /archetipi
      parent: Creazione del Personaggio
      weight: 4
    - name: Abilit√†
      pageRef: /abilita
      parent: Creazione del Personaggio
      weight: 5

    - name: Equipaggiamento
      pageRef: /equipaggiamento
      weight: 2

    - name: Talenti
      pageRef: /talenti
      weight: 3

    - name: Game Master
      weight: 4

    - name: Ambientazione
      weight: 5

    - name: Magia
      weight: 6

    - name: Regole
      pageRef: /regole
      weight: 10

build:
  buildStats:
    enable: true
  cachebusters:
    - source: assets/notwatching/hugo_stats\.json
      target: css
    - source: assets/.*\.(js|ts|jsx|tsx)
      target: js
  noJSConfigInAssets: true
enableInlineShortcodes: true
taxonomies:
markup:
  tableOfContents:
    startLevel: 1
  goldmark:
    extensions:
      extras:
        superscript:
          enable: true
        subscript:
          enable: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingIDType: github-ascii
    renderer:
      unsafe: true
timeout: 3000
module:
  mounts:
    - source: site/content
      target: content
    - source: site/assets
      target: assets
    - source: package.json
      target: assets/internal/package.json
    - source: site/layouts
      target: layouts
    - source: site/static
      target: static
    - source: sources
      target: assets/sources
    - source: hugo_stats.json
      target: assets/notwatching/hugo_stats.json
      disableWatch: true
ignoreLogs:
  - warning-rendershortcodes-in-html
outputs:
  home:
    - html
  page:
    - html
  section:
    - html
  taxonomy:
    - html
  term:
    - html
server:
  redirects:
    - fromre: "^(.*[^/])$"
      to: "$1/"
      status: 200
      force: true
