types:
  ancestry:
    path: "/stirpi/{{ .base }}"
  heritage:
    path: "/stirpi/{{ .params.ancestry }}/lignaggi/{{ .base }}"
  background:
    path: "/background/{{ .base }}"
    statblock: true
  class:
    path: "/classi/{{ .base }}"
  classfeature:
    path: "/classi/{{ .params.class }}/{{ .base }}"
  leadershipstyle:
    path: "/classi/emissario/stili-di-leadership/{{ .base }}"
  connection:
    path: "/classi/mistico/connessioni/{{ .base }}"
  specialization:
    path: "/classi/operativo/specializzazioni/{{ .base }}"
  fightingstyle:
    path: "/classi/soldato/stili-di-combattimento/{{ .base }}"
  anchor:
    path: "/classi/stregone-del-velo/ancore/{{ .base }}"
  paradox:
    path: "/classi/stregone-del-velo/paradossi/{{ .base }}"
  archetype:
    path: "/archetipi/{{ .base }}"
  feat:
    path: "/talenti/{{ .base }}"
    statblock: true
  action:
    path: "/azioni/{{ .base }}"
    statblock: true
  trait:
    path: "/tratti/{{ .base }}"
  spell:
    path: "/incantesimi/{{ .base }}"
    italic: true
  equipment:
    path: "/equipaggiamento/{{ .base }}"
    statblock: true
  subequipment:
    path: "/equipaggiamento/{{ .params.itemBase }}/{{ .base }}"
    statblock: true
  weapongroup:
    path: "/gruppi-armi/{{ .base }}"
  armorgroup:
    path: "/gruppi-armature/{{ .base }}"
  skill:
    path: "/abilita/{{ .base }}"
  planet:
    path: "/pianeti/{{ .base }}"
  condition:
    path: "/condizioni/{{ .base }}"

repoURL: https://github.com/n1xx1/sfitdb
repoBranch: main
